name = "vite-org"
type = "webpack"
account_id = "55cb4036f82767a7f0f757a02a1ec8fd"
workers_dev = true
main = "workers-site/index.js"
compatibility_date = "2023-07-22"

[site]
bucket = "./dist"

[env.production]
route = "vite.org/*"
zone_id = "f88e2f1d3639975a214cd2a56eefba13"

[env.test]
route = "test.vite.org/*"
zone_id = "f88e2f1d3639975a214cd2a56eefba13"