name = "vite-org-new-test"
main = "./.output/server/index.mjs"
workers_dev = true
account_id = "55cb4036f82767a7f0f757a02a1ec8fd"
compatibility_date = "2023-07-22"
route = { pattern = "test.vite.org/*", zone_name = "vite.org" }

[site]
bucket = ".output/public"

[env.production]
name = "vite-org-new"
route = { pattern = "vite.org/*", zone_name = "vite.org" }
